# Generated by Django 2.1.1 on 2019-02-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('key1', models.CharField(blank='true', max_length=255)),
                ('key2', models.CharField(blank='true', max_length=255)),
                ('key3', models.CharField(blank='true', max_length=255)),
                ('key4', models.CharField(blank='true', max_length=255)),
                ('key5', models.CharField(blank='true', max_length=255)),
                ('key6', models.CharField(blank='true', max_length=255)),
                ('key7', models.CharField(blank='true', max_length=255)),
                ('key8', models.CharField(blank='true', max_length=255)),
                ('key9', models.CharField(blank='true', max_length=255)),
                ('key10', models.CharField(blank='true', max_length=255)),
                ('exkey1', models.CharField(blank='true', max_length=255)),
                ('exkey2', models.CharField(blank='true', max_length=255)),
                ('exkey3', models.CharField(blank='true', max_length=255)),
                ('exkey4', models.CharField(blank='true', max_length=255)),
                ('exkey5', models.CharField(blank='true', max_length=255)),
                ('exkey6', models.CharField(blank='true', max_length=255)),
                ('exkey7', models.CharField(blank='true', max_length=255)),
                ('exkey8', models.CharField(blank='true', max_length=255)),
                ('exkey9', models.CharField(blank='true', max_length=255)),
                ('exkey10', models.CharField(blank='true', max_length=255)),
                ('notification_duration', models.IntegerField(blank='true')),
                ('notification_email', models.CharField(blank='true', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('key1', models.TextField(blank='true')),
            ],
        ),
    ]
