# Generated by Django 2.1.1 on 2019-02-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_project_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fb_source',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='inst_source',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='twit_source',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='you_source',
            field=models.BooleanField(default=0),
        ),
    ]
