# Generated by Django 2.1.1 on 2019-03-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='source',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
