# Generated by Django 2.1.1 on 2019-03-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_comment_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='gender',
            field=models.CharField(default='male', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='language',
            field=models.CharField(default='en', max_length=255),
            preserve_default=False,
        ),
    ]
