# Generated by Django 2.1.1 on 2019-03-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20190317_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sentiment',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
