# Generated by Django 2.1.1 on 2019-03-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20190322_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='intent',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='toxic',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
