# Generated by Django 2.1.1 on 2019-03-26 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20190325_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='intent',
            new_name='is_intent',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='toxic',
            new_name='is_toxic',
        ),
    ]
