# Generated by Django 2.1.1 on 2019-03-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20190326_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_intent',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_toxic',
            field=models.BooleanField(),
        ),
    ]
