# Generated by Django 2.1.1 on 2019-03-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20190326_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_intent',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_toxic',
            field=models.CharField(max_length=255),
        ),
    ]
