# Generated by Django 2.1.1 on 2019-03-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20190326_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_crisis',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
