# Generated by Django 2.1.1 on 2019-04-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_comment_is_crisis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='_message',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_name',
            new_name='_user_name',
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(db_column='title', max_length=255),
        ),
    ]
