# Generated by Django 2.1.1 on 2019-04-03 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20190403_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='_user_name',
            new_name='user_name',
        ),
    ]
