# Generated by Django 2.1.1 on 2019-04-03 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20190403_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_name',
            new_name='_user_name',
        ),
    ]
