# Generated by Django 2.1.1 on 2019-04-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20190403_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='_message',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='_user_name',
        ),
        migrations.AddField(
            model_name='comment',
            name='user_name',
            field=models.BinaryField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
